### ISSUE TITLE
Важно: в Player на ПК картинка слишком большая

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#201]
в Player на ПК картинка слишком большая, так что не лезут кнопки управления плеером. При изменение масштаба экрана, картинка не масштабируется. Исправляем.

![Снимок экрана 2023-04-11 144229](https://user-images.githubusercontent.com/103753072/231152649-411548b2-81a0-40a4-8850-b4423c6ae794.png)

**Comment by flancer64** [comment]
На данный момент размеры элемента IMG для вывода кадров анимации определяются через [стили](https://github.com/flancer32/pwa-ra-mob/blob/main/web/css/player.css#L4):
```css
.ra-player .ra-anime-img {
    border-radius: 8px;
    height: min(100%, 90vh);
    width: min(100%, 60vw);
}
```

можно просто добавить ограничение в пикселях на рамеры картинки. Например так:
```css
.ra-player .ra-anime-img {
    border-radius: 8px;
    height: min(100%, 90vh, 400px);
    width: min(100%, 60vw, 400px);
}
```

Если 400px много, то можно ещё больше ограничить. 

Это самый быстрый способ. Если нужно что-то более гибкое, то есть смысл добавить к изображению кнопки +/- и позволить пользователю самому изменять масштаб изображения анимации независимо от масштаба остальной страницы:
```js
image.style.width = '500px';
```

Если стиль задётся в пикселях, то начинает работать и масштабирование картинки при масштабировании всей страницы.
